import random
import uuid


def generate_unique_value(value: str) -> str:
    """Generate a unique value by appending a random suffix to the given value

    Args:
        value (str): the base value to which a unique suffix will be appended

    Returns:
        str: a unique value generated by appending a random suffix to the given value
    """
    random_suffix = uuid.uuid4().hex[:8]  # Generate a random 8-character suffix
    unique_value = f"{value}_{random_suffix}"  # Append the suffix to the base value
    return unique_value

def generate_unique_validator_version() -> str:
    """Generate a unique validator version x.x.x format by creating a random version number"""
    return f"{random.randint(0, 20)}.{random.randint(0, 40)}.{random.randint(0, 99)}"
